### ISSUE TITLE
resources can not be edited anymore

### ISSUE THREAD

**Issue by patrickmohrmann** [jessev14/resource-icons#14] opened 2022-07-28 09:04 UTC
![image](https://user-images.githubusercontent.com/76265425/181466872-78636046-e4b4-4d60-b629-f4724f5eb35d.png)

I miss the configuration possibility of the resource icons after the update

**Comment by jessev14** [comment] 2022-07-28 21:32
It's caused by Bar Brawl. I'll have to look into it later.

**Comment by jessev14** [comment] 2022-07-28 22:15
fixed in version 2.1.2

**Closed as completed by jessev14** 2022-07-28 22:16 UTC

**Comment by patrickmohrmann** [comment] 2022-08-04 08:26
thanks, great!
